const firebaseErrors = {
  'auth/admin-restricted-operation':
    'Operação permitida apenas para administradores',
  'auth/argument-error': 'Erro de argumento',
  'auth/app-not-authorized': 'Aplicativo não autorizado',
  'auth/app-not-installed': 'Aplicativo não instalado',
  'auth/captcha-check-failed': 'Verificação de Captcha falhou',
  'auth/code-expired': 'Código expirado',
  'auth/cordova-not-ready': 'Cordova não está pronto',
  'auth/cors-unsupported': 'CORS não suportado',
  'auth/credential-already-in-use': 'Credencial já em uso',
  'auth/custom-token-mismatch': 'Incompatibilidade de credencial',
  'auth/requires-recent-login': 'Credencial muito antiga, faça login novamente',
  'auth/dependent-sdk-initialized-before-auth':
    'SDK dependente inicializado antes da Autenticação',
  'auth/dynamic-link-not-activated': 'Link dinâmico não ativado',
  'auth/email-change-needs-verification':
    'Alteração de e-mail requer verificação',
  'auth/email-already-in-use': 'E-mail já em uso',
  'auth/emulator-config-failed': 'Falha na configuração do emulador',
  'auth/expired-action-code': 'Código de ação expirado',
  'auth/cancelled-popup-request': 'Solicitação de popup expirada',
  'auth/internal-error': 'Erro interno',
  'auth/invalid-api-key': 'Chave API inválida',
  'auth/invalid-app-credential': 'Credencial de aplicativo inválida',
  'auth/invalid-app-id': 'ID de aplicativo inválido',
  'auth/invalid-user-token': 'Autenticação inválida',
  'auth/invalid-auth-event': 'Evento de autenticação inválido',
  'auth/invalid-cert-hash': 'Hash de certificado inválido',
  'auth/invalid-verification-code': 'Código inválido',
  'auth/invalid-continue-uri': 'URI de continuação inválida',
  'auth/invalid-cordova-configuration': 'Configuração Cordova inválida',
  'auth/invalid-custom-token': 'Token personalizado inválido',
  'auth/invalid-dynamic-link-domain': 'Domínio de link dinâmico inválido',
  'auth/invalid-email': 'E-mail inválido',
  'auth/invalid-emulator-scheme': 'Esquema de emulador inválido',
  'auth/invalid-credential': 'Login inválido',
  'auth/invalid-message-payload': 'Payload de mensagem inválido',
  'auth/invalid-multi-factor-session': 'Sessão de MFA inválida',
  'auth/invalid-oauth-client-id': 'ID do cliente OAuth inválido',
  'auth/invalid-oauth-provider': 'Provedor OAuth inválido',
  'auth/invalid-action-code': 'Código OOB inválido',
  'auth/unauthorized-domain': 'Origem inválida',
  'auth/wrong-password': 'Senha incorreta',
  'auth/invalid-persistence-type': 'Persistência inválida',
  'auth/invalid-phone-number': 'Número de telefone inválido',
  'auth/invalid-provider-id': 'ID do provedor inválido',
  'auth/invalid-recipient-email': 'E-mail do destinatário inválido',
  'auth/invalid-sender': 'Remetente inválido',
  'auth/invalid-verification-id': 'Informações de sessão inválidas',
  'auth/invalid-tenant-id': 'ID de locatário inválido',
  'auth/multi-factor-info-not-found': 'Informações MFA não encontradas',
  'auth/multi-factor-auth-required': 'MFA necessário',
  'auth/missing-android-pkg-name': 'Nome do pacote Android ausente',
  'auth/missing-app-credential': 'Credencial de aplicativo ausente',
  'auth/auth-domain-config-required': 'Domínio de Autenticação ausente',
  'auth/missing-verification-code': 'Código ausente',
  'auth/missing-continue-uri': 'URI de continuação ausente',
  'auth/missing-iframe-start': 'Início do iframe ausente',
  'auth/missing-ios-bundle-id': 'ID do pacote iOS ausente',
  'auth/missing-or-invalid-nonce': 'Nonce ausente ou inválido',
  'auth/missing-multi-factor-info': 'Informações MFA ausentes',
  'auth/missing-multi-factor-session': 'Sessão MFA ausente',
  'auth/missing-phone-number': 'Número de telefone ausente',
  'auth/missing-verification-id': 'Informações de sessão ausentes',
  'auth/app-deleted': 'Módulo destruído',
  'auth/account-exists-with-different-credential': 'Necessita de confirmação',
  'auth/network-request-failed': 'Falha na solicitação de rede',
  'auth/null-user': 'Usuário nulo',
  'auth/no-auth-event': 'Nenhum evento de autenticação',
  'auth/no-such-provider': 'Nenhum provedor encontrado',
  'auth/operation-not-allowed': 'Operação não permitida',
  'auth/operation-not-supported-in-this-environment':
    'Operação não suportada neste ambiente',
  'auth/popup-blocked': 'Popup bloqueado',
  'auth/popup-closed-by-user': 'Popup fechado pelo usuário',
  'auth/provider-already-linked': 'Provedor já vinculado',
  'auth/quota-exceeded': 'Cota excedida',
  'auth/redirect-cancelled-by-user': 'Redirecionamento cancelado pelo usuário',
  'auth/redirect-operation-pending': 'Operação de redirecionamento pendente',
  'auth/rejected-credential': 'Credencial rejeitada',
  'auth/second-factor-already-in-use': 'Segundo fator já registrado',
  'auth/maximum-second-factor-count-exceeded':
    'Limite máximo de segundo fator excedido',
  'auth/tenant-id-mismatch': 'Incompatibilidade no ID do locatário',
  'auth/timeout': 'Tempo limite',
  'auth/user-token-expired': 'Token de usuário expirado',
  'auth/too-many-requests': 'Muitas tentativas, tente novamente mais tarde',
  'auth/unauthorized-continue-uri': 'Domínio não autorizado',
  'auth/unsupported-first-factor': 'Primeiro fator não suportado',
  'auth/unsupported-persistence-type': 'Persistência não suportada',
  'auth/unsupported-tenant-operation': 'Operação de locatário não suportada',
  'auth/unverified-email': 'E-mail não verificado',
  'auth/user-cancelled': 'Usuário cancelou',
  'auth/user-not-found': 'Usuário não encontrado',
  'auth/user-disabled': 'Usuário desativado',
  'auth/user-mismatch': 'Incompatibilidade de usuário',
  'auth/user-signed-out': 'Usuário desconectado',
  'auth/weak-password': 'Senha fraca (mín. 6 dígitos)',
  'auth/web-storage-unsupported': 'Armazenamento na web não suportado',
  'auth/already-initialized': 'Já inicializado',
  'auth/recaptcha-not-enabled': 'Recaptcha não habilitado',
  'auth/missing-recaptcha-token': 'Token Recaptcha ausente',
  'auth/invalid-recaptcha-token': 'Token Recaptcha inválido',
  'auth/invalid-recaptcha-action': 'Ação Recaptcha inválida',
  'auth/missing-client-type': 'Tipo de cliente ausente',
  'auth/missing-recaptcha-version': 'Versão Recaptcha ausente',
  'auth/invalid-recaptcha-version': 'Versão Recaptcha inválida',
  'auth/invalid-req-type': 'Tipo de solicitação inválido'
};

export default firebaseErrors;
